import type { ICategory } from './types';

export const CATEGORIES: ICategory[] = [
  {
    id: 'ia',
    slug: 'ia',
    name: { en: 'Artificial Intelligence', fr: 'Intelligence Artificielle' },
    description: { en: 'AI resources', fr: 'Ressources IA' },
    icon: 'Brain',
    color: 'text-purple-400',
    bgColor: 'bg-purple-400/10',
    resourceCount: 0,
  },
  {
    id: 'ml',
    slug: 'ml',
    name: { en: 'Machine Learning', fr: 'Machine Learning' },
    description: { en: 'ML resources', fr: 'Ressources ML' },
    icon: 'TrendingUp',
    color: 'text-brand-400',
    bgColor: 'bg-blue-400/10',
    resourceCount: 0,
  },
  {
    id: 'dl',
    slug: 'dl',
    name: { en: 'Deep Learning', fr: 'Deep Learning' },
    description: { en: 'DL resources', fr: 'Ressources DL' },
    icon: 'Network',
    color: 'text-pink-400',
    bgColor: 'bg-pink-400/10',
    resourceCount: 0,
  },
  {
    id: 'web',
    slug: 'web',
    name: { en: 'Web Development', fr: 'Developpement Web' },
    description: { en: 'Web resources', fr: 'Ressources Web' },
    icon: 'Globe',
    color: 'text-brand-400',
    bgColor: 'bg-brand-400/10',
    resourceCount: 0,
  },
  {
    id: 'mobile',
    slug: 'mobile',
    name: { en: 'Mobile Development', fr: 'Developpement Mobile' },
    description: { en: 'Mobile resources', fr: 'Ressources Mobile' },
    icon: 'Smartphone',
    color: 'text-orange-400',
    bgColor: 'bg-orange-400/10',
    resourceCount: 0,
  },
  {
    id: 'data',
    slug: 'data',
    name: { en: 'Data Science', fr: 'Data Science' },
    description: { en: 'Data resources', fr: 'Ressources Data' },
    icon: 'Database',
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-400/10',
    resourceCount: 0,
  },
];

export const TAGS = [
  { id: 'python', name: 'Python', color: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30', resourceCount: 5 },
  { id: 'tensorflow', name: 'TensorFlow', color: 'bg-orange-500/20 text-orange-400 border-orange-500/30', resourceCount: 3 },
  { id: 'pytorch', name: 'PyTorch', color: 'bg-red-500/20 text-red-400 border-red-500/30', resourceCount: 4 },
  { id: 'react', name: 'React', color: 'bg-cyan-500/20 text-cyan-400 border-cyan-500/30', resourceCount: 2 },
  { id: 'javascript', name: 'JavaScript', color: 'bg-yellow-500/20 text-yellow-400 border-yellow-500/30', resourceCount: 3 },
  { id: 'nlp', name: 'NLP', color: 'bg-indigo-500/20 text-indigo-400 border-indigo-500/30', resourceCount: 2 },
  { id: 'cv', name: 'Computer Vision', color: 'bg-purple-500/20 text-purple-400 border-purple-500/30', resourceCount: 2 },
  { id: 'sql', name: 'SQL', color: 'bg-brand-500/15 text-brand-400 border-brand-500/25', resourceCount: 2 },
];
